import type { ApplicationWizardValues } from "@/modules/applications/schema";

export type PmApplicationDetail = {
  applicationNumber: string;
  verificationType: string;
  applicationCategory: string;
  createdAt: string;
  payload: ApplicationWizardValues;
  businessAddress: string | null;
  company: { companyName: string; nibNumber: string; kbliEntries: { code: string; description: string }[]; sktNumber: string | null };
  stage: string;
  status: string;
  slaLabel: string;
  slaDetail: string;
  slaColor: string;
  assignments: {
    survey: {
      id: string;
      assignmentNumber: string;
      status: string;
      surveyorName: string | null;
      scheduledDate: string | null;
      location: string | null;
      letterStatus: string;
      letterNumber: string | null;
      letterReviewNote: string | null;
      pmReviewStatus: string | null;
      pmReviewNote: string | null;
      pmReviewedAt: string | null;
      allLocationsCompleted: boolean;
      locationVisits: {
        id: string;
        locationType: string;
        address: string;
        city: string | null;
        status: string;
        assignmentNumber: string;
        scheduledDate: string | null;
        submittedAt: string | null;
        findingsCount: number;
        surveyorConclusion: string | null;
        decision: "VERIFIED" | "REJECTED" | "REVISION" | null;
        decisionNote: string | null;
        verifiedByName: string | null;
        verifiedAt: string | null;
      }[];
    } | null;
    dokumen: {
      id: string;
      assignmentNumber: string;
      status: string;
      verifikatorName: string | null;
      scheduledDate: string | null;
      location: string | null;
      letterStatus: string;
      letterNumber: string | null;
      letterReviewNote: string | null;
      pmReviewStatus: string | null;
      pmReviewNote: string | null;
      pmReviewedAt: string | null;
      validatedAt: string | null;
    } | null;
    technical: {
      id: string;
      assignmentNumber: string;
      status: string;
      technicalReviewerName: string | null;
      scheduledDate: string | null;
      location: string | null;
      letterStatus: string;
      letterNumber: string | null;
      letterReviewNote: string | null;
      pmReviewStatus: string | null;
      pmReviewNote: string | null;
      pmReviewedAt: string | null;
      validatedAt: string | null;
      technicalAnalysisData: Record<string, { status?: string; keterangan?: string; kesimpulan?: string; inputs?: Record<string, string> }>;
    } | null;
  };
  documentChecklist: {
    key: string;
    label: string;
    category: string;
    documentPath: string | null;
    hasDocument: boolean;
    status: string;
    uploadedAt: string | null;
    verifiedByName: string | null;
    verifiedByRole: string | null;
    verifiedAt: string | null;
  }[];
  machines: {
    id: string;
    nama: string;
    proses: string;
    merk: string;
    model: string;
    tahun: string;
    quantity: string;
    quantitySatuan: string;
    kapasitas: string;
    kapasitasSatuan: string;
    kapasitasJam: string;
    kapasitasJamSatuan: string;
    waktuBeroperasi: string;
    kapasitasPerHari: string;
    kondisi: string;
    power: string;
    powerSatuan: string;
    input: string;
    output: string;
    photoMesinPath: string | null;
    status: string;
    note: string;
    verifiedAt: string | null;
  }[];
  products: {
    id: string;
    materialType: string;
    hsCode: string;
    hsDesc: string;
    deskripsi: string;
    kategori: string;
    status: string;
    note: string;
    verifiedAt: string | null;
    photoPath: string | null;
  }[];
  capacity: { productId: string; jenisProduk: string; hsCode: string; berdasarkanIzin: string; kapasitasTerpasang: string; satuan: string }[];
  capacityDocumentPath: string | null;
  productionQty: { key: string; section: string; jenisProduk: string; hsCode: string; jumlah: string; satuan: string; status: string }[];
  rawMaterialUsage: { id: string; jenis: string; hsCode: string; productName: string; penggunaan: string; dataStock: string; rencanaKebutuhan: string; satuan: string }[];
  rawMaterialConversion: {
    id: string;
    productId: string | null;
    productName: string;
    productHsCode: string;
    jenis: string;
    hsCode: string;
    hsDesc: string;
    deskripsi: string;
    photoPath: string | null;
    kategori: string;
    volumeKebutuhanJumlah: string;
    volumeKebutuhanSatuan: string;
    volumeProduksiJumlah: string;
    volumeProduksiSatuan: string;
    rasioKonversi: string;
    keterangan: string;
  }[];
  sales: { id: string; productName: string; dalamNegeri: string; luarNegeri: string; satuan: string }[];
  timeline: { title: string; time: string }[];
};
